### ISSUE TITLE
Design v2

### ISSUE THREAD

**Issue by CyberStrike** [Code-for-Miami/project-landing-page-template#3]
Another design revision to the page design going from a single column to a responsive two column layout.

![image](https://user-images.githubusercontent.com/1733501/33530949-a45b407c-d854-11e7-83aa-8b8c139edfa6.png)

**Resources**
[Project Landing Page Template - Google Drive](https://drive.google.com/open?id=11VlzjFoAkUPoinNyUeKZ8En9qOMzOSPy) [Sketch, Logos, and other assets]

**Comment by codebycody-zz** [comment]
@CyberStrike  I just merged this because it was a simple change, if you would like me to make a new branch regardless of the change size/project I'll be happy to in the future. Second thought I'm going to just do that because it will set a good example.
